// Package custom implements a free-form template driver: the user pastes a
// docker-compose.yml body and (optionally) an .env block, and the service
// renders them verbatim. There is no schema beyond "must parse as YAML and
// declare a services map", so users can deploy arbitrary stacks without
// needing a built-in driver. Project name / slug isolation, lifecycle
// management and host port collision checks all work the same as for the
// other drivers — the compose project name is pinned via --project-name in
// the Compose helper, regardless of what the YAML says.
package custom

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/ANASDAVOODTK/server-monitor/internal/templates"
	"gopkg.in/yaml.v3"
)

type Driver struct{}

func New() *Driver { return &Driver{} }

func (d *Driver) Definition() templates.Definition {
	return templates.Definition{
		ID:          "custom",
		Name:        "Custom (paste compose)",
		Description: "Bring your own docker-compose.yml and .env. Deployed as an isolated project with the same lifecycle controls as built-in templates.",
		Fields: []templates.Field{
			{
				Key:         "compose",
				Label:       "docker-compose.yml",
				Type:        templates.FieldTextarea,
				Required:    true,
				Description: "Paste a complete docker-compose.yml. Use ${VAR} to reference values from the env block below.",
				Placeholder: customComposePlaceholder,
				Group:       "compose",
			},
			{
				Key:         "env",
				Label:       ".env (optional)",
				Type:        templates.FieldTextarea,
				Required:    false,
				Description: "One KEY=value per line. Values are substituted into the compose file by docker compose.",
				Placeholder: "EXAMPLE_KEY=value\n",
				Group:       "compose",
			},
		},
		Ports:          []templates.PortField{},
		SupportsUpdate: true,
	}
}

func (d *Driver) Validate(input templates.DeployInput) error {
	compose := strings.TrimSpace(input.Config["compose"])
	if compose == "" {
		return fmt.Errorf("docker-compose.yml is required")
	}
	var parsed map[string]any
	if err := yaml.Unmarshal([]byte(compose), &parsed); err != nil {
		return fmt.Errorf("compose: invalid YAML: %w", err)
	}
	services, ok := parsed["services"].(map[string]any)
	if !ok || len(services) == 0 {
		return fmt.Errorf("compose: must declare at least one entry under 'services:'")
	}
	if err := validateEnvBlock(input.Config["env"]); err != nil {
		return err
	}
	for k := range input.Env {
		if !envKeyRe.MatchString(k) {
			return fmt.Errorf("invalid env var name %q (use A-Z, 0-9, _; must start with a letter)", k)
		}
	}
	return nil
}

func (d *Driver) Render(dep *templates.Deployment) (templates.RenderedArtifacts, error) {
	compose := strings.TrimSpace(dep.Config["compose"])

	var env strings.Builder
	env.WriteString("# Auto-generated by server-monitor. Edit via the Templates UI.\n")
	if user := strings.TrimSpace(dep.Config["env"]); user != "" {
		env.WriteString(user)
		if !strings.HasSuffix(user, "\n") {
			env.WriteString("\n")
		}
	}
	for k, v := range dep.Env {
		fmt.Fprintf(&env, "%s=%s\n", k, v)
	}

	return templates.RenderedArtifacts{
		Compose: compose + "\n",
		Env:     env.String(),
	}, nil
}

// validateEnvBlock ensures every non-blank line in the pasted env body is a
// KEY=value pair with a sane key. Lines starting with '#' are treated as
// comments and skipped.
func validateEnvBlock(body string) error {
	for i, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		eq := strings.IndexByte(trimmed, '=')
		if eq <= 0 {
			return fmt.Errorf("env line %d: expected KEY=value, got %q", i+1, line)
		}
		key := strings.TrimSpace(trimmed[:eq])
		if !envKeyRe.MatchString(key) {
			return fmt.Errorf("env line %d: invalid key %q (use A-Z, 0-9, _; must start with a letter)", i+1, key)
		}
	}
	return nil
}

var envKeyRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]{0,63}$`)

const customComposePlaceholder = `services:
  app:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
`
