package supabase

import (
	"strings"

	"github.com/ANASDAVOODTK/server-monitor/internal/templates"
)

// Layout of the Edge Functions runtime inside a deployment workdir. The
// source dir is bind-mounted into both Studio (/app/edge-functions) and the
// edge runtime (/home/deno/functions) so they see the same files.
const (
	functionsSourceDir   = "volumes/functions"
	functionsEnvFile     = ".env.functions"
	functionsSecretsDir  = "volumes/secrets"
	functionsSecretMount = "/run/secrets"
	functionsService     = "functions"
	functionsRuntimeTag  = "supabase/edge-runtime:v1.76.2"
)

// FunctionsLayout implements templates.FunctionsSupport.
func (d *Driver) FunctionsLayout(dep *templates.Deployment) (templates.FunctionsLayout, bool) {
	if !functionsEnabled(dep.Config) {
		return templates.FunctionsLayout{}, false
	}
	return templates.FunctionsLayout{
		SourceDir:        functionsSourceDir,
		SecretsEnvFile:   functionsEnvFile,
		SecretFilesDir:   functionsSecretsDir,
		SecretFilesMount: functionsSecretMount,
		Service:          functionsService,
		RoutePrefix:      "/functions/v1/",
		System:           []string{"main", "deno.jsonc"},
		// Mirrors the `environment:` block of the functions service.
		ReservedEnv:         []string{"JWT_SECRET", "VERIFY_JWT"},
		ReservedEnvPrefixes: []string{"SUPABASE_"},
	}, true
}

// functionsEnabled reports whether the edge runtime is part of this
// deployment. Empty means the Definition default ("yes"), so deployments
// created before the field existed get functions on their next start.
func functionsEnabled(cfg map[string]string) bool { return yesDefault(cfg["functions_enabled"]) }

// functionsVerifyJWT maps the functions_verify_jwt field to the VERIFY_JWT
// value the main worker reads.
func functionsVerifyJWT(cfg map[string]string) string {
	if yesDefault(cfg["functions_verify_jwt"]) {
		return "true"
	}
	return "false"
}

func yesDefault(v string) bool {
	v = strings.ToLower(strings.TrimSpace(v))
	if v == "" {
		return true
	}
	return v == "yes" || v == "true" || v == "1" || v == "on"
}

// functionsSeedFiles is the runtime plumbing written only when missing, so
// user edits survive re-renders.
func functionsSeedFiles() map[string]string {
	return map[string]string{
		functionsSourceDir + "/main/index.ts": mainWorkerTS,
		functionsSourceDir + "/deno.jsonc":    denoJSONC,
		functionsEnvFile:                      functionsEnvSeed,
	}
}

// mainWorkerTS is the Supabase self-hosting main worker: it verifies the
// caller's JWT (when VERIFY_JWT=true) and dispatches /<name> to the function
// in /home/deno/functions/<name>. Embedded instead of downloaded from the
// supabase repo's master branch so every deployment gets the same revision,
// known to work with functionsRuntimeTag.
const mainWorkerTS = `// Main worker for the Supabase Edge Runtime. Generated by server-monitor.
// Routes /<function-name> to /home/deno/functions/<function-name>.
import * as jose from 'https://deno.land/x/jose@v4.14.4/index.ts'

console.log('main function started')

const JWT_SECRET = Deno.env.get('JWT_SECRET')
const VERIFY_JWT = Deno.env.get('VERIFY_JWT') === 'true'

function getAuthToken(req: Request) {
  const authHeader = req.headers.get('authorization')
  if (!authHeader) {
    throw new Error('Missing authorization header')
  }
  const [bearer, token] = authHeader.split(' ')
  if (bearer !== 'Bearer') {
    throw new Error("Auth header is not 'Bearer {token}'")
  }
  return token
}

async function verifyJWT(jwt: string): Promise<boolean> {
  const encoder = new TextEncoder()
  const secretKey = encoder.encode(JWT_SECRET)
  try {
    await jose.jwtVerify(jwt, secretKey)
  } catch (err) {
    console.error(err)
    return false
  }
  return true
}

Deno.serve(async (req: Request) => {
  if (req.method !== 'OPTIONS' && VERIFY_JWT) {
    try {
      const token = getAuthToken(req)
      const isValidJWT = await verifyJWT(token)

      if (!isValidJWT) {
        return new Response(JSON.stringify({ msg: 'Invalid JWT' }), {
          status: 401,
          headers: { 'Content-Type': 'application/json' },
        })
      }
    } catch (e) {
      console.error(e)
      return new Response(JSON.stringify({ msg: e.toString() }), {
        status: 401,
        headers: { 'Content-Type': 'application/json' },
      })
    }
  }

  const url = new URL(req.url)
  const { pathname } = url
  const path_parts = pathname.split('/')
  const service_name = path_parts[1]

  if (!service_name || service_name === '') {
    const error = { msg: 'missing function name in request' }
    return new Response(JSON.stringify(error), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    })
  }

  const servicePath = ` + "`/home/deno/functions/${service_name}`" + `
  console.error(` + "`serving the request with ${servicePath}`" + `)

  const memoryLimitMb = 150
  const workerTimeoutMs = 1 * 60 * 1000
  const noModuleCache = false
  const importMapPath = null
  const envVarsObj = Deno.env.toObject()
  const envVars = Object.keys(envVarsObj).map((k) => [k, envVarsObj[k]])

  try {
    const worker = await EdgeRuntime.userWorkers.create({
      servicePath,
      memoryLimitMb,
      workerTimeoutMs,
      noModuleCache,
      importMapPath,
      envVars,
    })
    return await worker.fetch(req)
  } catch (e) {
    const error = { msg: e.toString() }
    return new Response(JSON.stringify(error), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }
})
`

const denoJSONC = `{
  // Shared import map for every function in this directory, e.g.
  //   "@supabase/supabase-js": "jsr:@supabase/supabase-js@2"
  "imports": {}
}
`

const functionsEnvSeed = `# Edge Function secrets. Managed by server-monitor from the deployment page.
# Read inside a function with Deno.env.get("KEY").
`
