package supabase

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// initSQLTpl is rendered per-deployment with the password / JWT secret baked
// in (and SQL-quote-escaped). The resulting file is mounted into a one-shot
// `db-init` sidecar that waits for supabase/postgres to finish provisioning
// its internal roles, then runs `psql -f /init.sql` against the live DB.
//
// We deliberately do NOT rely on /docker-entrypoint-initdb.d/ files because
// those only fire on a brand-new Postgres data directory. The sidecar runs
// every time the stack starts, is fully idempotent, and recovers data dirs
// created by previous broken deploys.
var initSQLTpl = template.Must(template.New("initsql").Parse(`-- Auto-generated by server-monitor. Idempotent password / schema sync for
-- one Supabase project. Safe to re-run.

-- Align every Supabase-managed role's password with POSTGRES_PASSWORD. The
-- role accounts themselves are created by the supabase/postgres image's
-- own bootstrap, so we only ALTER what's already there - missing roles are
-- skipped instead of failing the script.
DO $supabase$
DECLARE
    role_name text;
    pw constant text := '{{ .PostgresPassword }}';
BEGIN
    FOREACH role_name IN ARRAY ARRAY[
        'authenticator',
        'pgbouncer',
        'supabase_auth_admin',
        'supabase_functions_admin',
        'supabase_storage_admin',
        'supabase_admin',
        'supabase_read_only_user',
        'supabase_replication_admin'
    ]
    LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
            EXECUTE format('ALTER USER %I WITH PASSWORD %L', role_name, pw);
            RAISE NOTICE 'updated password for %', role_name;
        ELSE
            RAISE NOTICE 'role % missing, skipping', role_name;
        END IF;
    END LOOP;
END
$supabase$;

-- Publish JWT settings so RLS using auth.jwt() works.
ALTER DATABASE postgres SET "app.settings.jwt_secret" TO '{{ .JWTSecret }}';
ALTER DATABASE postgres SET "app.settings.jwt_exp" TO '3600';

-- Schemas relied on by realtime / database webhooks.
CREATE SCHEMA IF NOT EXISTS _realtime;
CREATE SCHEMA IF NOT EXISTS supabase_functions;
GRANT USAGE ON SCHEMA supabase_functions TO postgres;
`))

// renderInitSQL produces the per-deployment init.sql with secrets baked in.
// Single quotes are doubled so the resulting SQL is safe regardless of the
// characters a user typed into the password / secret fields.
func renderInitSQL(postgresPassword, jwtSecret string) (string, error) {
	data := struct {
		PostgresPassword string
		JWTSecret        string
	}{
		PostgresPassword: sqlEscape(postgresPassword),
		JWTSecret:        sqlEscape(jwtSecret),
	}
	buf := &bytes.Buffer{}
	if err := initSQLTpl.Execute(buf, data); err != nil {
		return "", fmt.Errorf("init.sql render: %w", err)
	}
	return buf.String(), nil
}

// sqlEscape doubles single quotes for safe interpolation into a SQL string
// literal (the only escape required by Postgres when standard_conforming_strings
// is on, which is the default since 9.1).
func sqlEscape(s string) string { return strings.ReplaceAll(s, "'", "''") }
