package supabase

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// initSQLTpl is rendered per-deployment with the password / JWT secret baked
// in (and SQL-quote-escaped). The resulting file is mounted into a one-shot
// `db-init` sidecar that runs `psql -f /init.sql` against the live database.
//
// We deliberately do NOT rely on /docker-entrypoint-initdb.d/ files: those
// only fire on a brand-new Postgres data directory. The sidecar runs every
// time the stack starts, is fully idempotent, and works even if the volume
// was created by a previous broken deploy.
var initSQLTpl = template.Must(template.New("initsql").Parse(`-- Auto-generated by server-monitor. Idempotent setup for one Supabase project.

-- Align every Supabase-managed role's password with POSTGRES_PASSWORD. The
-- role accounts themselves are created by the supabase/postgres image, so
-- we just ALTER them.
DO $$
DECLARE
    pw text := '{{ .PostgresPassword }}';
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticator') THEN
        EXECUTE format('ALTER USER authenticator WITH PASSWORD %L', pw);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pgbouncer') THEN
        EXECUTE format('ALTER USER pgbouncer WITH PASSWORD %L', pw);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_auth_admin') THEN
        EXECUTE format('ALTER USER supabase_auth_admin WITH PASSWORD %L', pw);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_functions_admin') THEN
        EXECUTE format('ALTER USER supabase_functions_admin WITH PASSWORD %L', pw);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_storage_admin') THEN
        EXECUTE format('ALTER USER supabase_storage_admin WITH PASSWORD %L', pw);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_admin') THEN
        EXECUTE format('ALTER USER supabase_admin WITH PASSWORD %L', pw);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_read_only_user') THEN
        EXECUTE format('ALTER USER supabase_read_only_user WITH PASSWORD %L', pw);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_replication_admin') THEN
        EXECUTE format('ALTER USER supabase_replication_admin WITH PASSWORD %L', pw);
    END IF;
END $$;

-- Roles required by Supabase that might not exist if the image's own init
-- did not run (older images / customized data dirs).
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        CREATE ROLE anon NOLOGIN NOINHERIT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        CREATE ROLE authenticated NOLOGIN NOINHERIT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
        CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticator') THEN
        EXECUTE format('CREATE ROLE authenticator LOGIN NOINHERIT PASSWORD %L', '{{ .PostgresPassword }}');
        GRANT anon, authenticated, service_role TO authenticator;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_auth_admin') THEN
        EXECUTE format('CREATE ROLE supabase_auth_admin LOGIN CREATEROLE PASSWORD %L', '{{ .PostgresPassword }}');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_storage_admin') THEN
        EXECUTE format('CREATE ROLE supabase_storage_admin LOGIN CREATEROLE PASSWORD %L', '{{ .PostgresPassword }}');
    END IF;
END $$;

-- Publish JWT settings as DB GUCs so RLS using auth.jwt() works.
ALTER DATABASE postgres SET "app.settings.jwt_secret" TO '{{ .JWTSecret }}';
ALTER DATABASE postgres SET "app.settings.jwt_exp" TO '3600';

-- Schemas relied on by realtime / database webhooks. CREATE IF NOT EXISTS
-- keeps the script idempotent across restarts.
CREATE SCHEMA IF NOT EXISTS _realtime;
CREATE SCHEMA IF NOT EXISTS supabase_functions;
GRANT USAGE ON SCHEMA supabase_functions TO postgres, anon, authenticated, service_role;
`))

// renderInitSQL produces the per-deployment init.sql with secrets baked in.
// Single quotes are doubled so the resulting SQL is safe regardless of the
// characters a user typed into the password / secret fields.
func renderInitSQL(postgresPassword, jwtSecret string) (string, error) {
	data := struct {
		PostgresPassword string
		JWTSecret        string
	}{
		PostgresPassword: sqlEscape(postgresPassword),
		JWTSecret:        sqlEscape(jwtSecret),
	}
	buf := &bytes.Buffer{}
	if err := initSQLTpl.Execute(buf, data); err != nil {
		return "", fmt.Errorf("init.sql render: %w", err)
	}
	return buf.String(), nil
}

// sqlEscape doubles single quotes for safe interpolation into a SQL string
// literal (the only escape required by Postgres when standard_conforming_strings
// is on, which is the default since 9.1).
func sqlEscape(s string) string { return strings.ReplaceAll(s, "'", "''") }
