package qdrant

// qdrantComposeYAML is the docker-compose.yml template for one isolated Qdrant
// deployment. The compose project name is the template deployment slug, so
// multiple Qdrant instances can run side-by-side without collisions.
const qdrantComposeYAML = `# Auto-generated by server-monitor templates.
name: {{ .Dep.Slug }}

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "${QDRANT_HTTP_PORT}:6333"
      - "${QDRANT_GRPC_PORT}:6334"
      - "${QDRANT_P2P_PORT}:6335"
    expose:
      - "6333"
      - "6334"
      - "6335"
    volumes:
      - ./volumes/qdrant/storage:/qdrant/storage
      - ./volumes/qdrant/production.yaml:/qdrant/config/production.yaml:ro
`

const qdrantConfigYAML = `# Auto-generated by server-monitor templates.
log_level: {{ default .Config.log_level "INFO" }}
service:
  api_key: {{ quote (default .Config.api_key "") }}
`
