package qdrant

import (
	"bytes"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"text/template"

	"github.com/ANASDAVOODTK/server-monitor/internal/templates"
)

// Driver is the Qdrant template implementation.
type Driver struct{}

// New returns a ready-to-register Qdrant driver.
func New() *Driver { return &Driver{} }

func (d *Driver) Definition() templates.Definition {
	return templates.Definition{
		ID:          "qdrant",
		Name:        "Qdrant",
		Description: "Self-hosted Qdrant vector database deployed as an isolated project.",
		Icon:        "qdrant",
		Fields: []templates.Field{
			{Key: "project_name", Label: "Project name", Type: templates.FieldText, Required: true, Description: "Human-friendly name shown in the dashboard.", Placeholder: "my-qdrant", Group: "general"},
			{Key: "api_key", Label: "API key", Type: templates.FieldSecret, Required: true, Description: "Qdrant service API key used for client authentication.", Group: "security"},
			{Key: "log_level", Label: "Log level", Type: templates.FieldText, Required: false, Default: "INFO", Description: "Qdrant log level (e.g. INFO, DEBUG, WARN).", Group: "general"},
		},
		Ports: []templates.PortField{
			{Key: "http", Label: "HTTP API", Default: 6333, Description: "REST API host port."},
			{Key: "grpc", Label: "gRPC API", Default: 6334, Description: "gRPC API host port."},
			{Key: "p2p", Label: "P2P", Default: 6335, Description: "Internal peer-to-peer host port (single node can keep default)."},
		},
		SupportsUpdate: true,
	}
}

func (d *Driver) Validate(input templates.DeployInput) error {
	if strings.TrimSpace(input.Config["api_key"]) == "" {
		return fmt.Errorf("api_key is required")
	}
	if len(strings.TrimSpace(input.Config["api_key"])) < 16 {
		return fmt.Errorf("api_key must be at least 16 characters")
	}
	for k, v := range input.Ports {
		if v <= 0 || v > 65535 {
			return fmt.Errorf("invalid port %q: %d", k, v)
		}
	}
	for k := range input.Env {
		if !envKeyRe.MatchString(k) {
			return fmt.Errorf("invalid env var name %q (use A-Z, 0-9, _; must start with a letter)", k)
		}
	}
	return nil
}

func (d *Driver) Render(dep *templates.Deployment) (templates.RenderedArtifacts, error) {
	data := struct {
		Dep    *templates.Deployment
		Config map[string]string
		Ports  map[string]int
	}{Dep: dep, Config: dep.Config, Ports: dep.Ports}

	composeBuf := &bytes.Buffer{}
	if err := composeTpl.Execute(composeBuf, data); err != nil {
		return templates.RenderedArtifacts{}, fmt.Errorf("compose render: %w", err)
	}
	envBuf := &bytes.Buffer{}
	if err := envTpl.Execute(envBuf, data); err != nil {
		return templates.RenderedArtifacts{}, fmt.Errorf("env render: %w", err)
	}
	for k, v := range dep.Env {
		fmt.Fprintf(envBuf, "%s=%s\n", k, v)
	}
	cfgBuf := &bytes.Buffer{}
	if err := configTpl.Execute(cfgBuf, data); err != nil {
		return templates.RenderedArtifacts{}, fmt.Errorf("qdrant config render: %w", err)
	}

	return templates.RenderedArtifacts{
		Compose: composeBuf.String(),
		Env:     envBuf.String(),
		Files: map[string]string{
			"volumes/qdrant/production.yaml": cfgBuf.String(),
		},
	}, nil
}

var envTpl = template.Must(template.New("env").Funcs(template.FuncMap{
	"default": tmplDefault,
}).Parse(`# Auto-generated by server-monitor. Do not edit by hand.
QDRANT_API_KEY={{ .Config.api_key }}
QDRANT_LOG_LEVEL={{ default .Config.log_level "INFO" }}
QDRANT_HTTP_PORT={{ .Ports.http }}
QDRANT_GRPC_PORT={{ .Ports.grpc }}
QDRANT_P2P_PORT={{ .Ports.p2p }}
PROJECT_SLUG={{ .Dep.Slug }}
`))

var composeTpl = template.Must(template.New("compose").Parse(qdrantComposeYAML))

var configTpl = template.Must(template.New("qdrant-config").Funcs(template.FuncMap{
	"default": tmplDefault,
	"quote":   strconv.Quote,
}).Parse(qdrantConfigYAML))

func tmplDefault(value any, fallback string) string {
	switch v := value.(type) {
	case string:
		if strings.TrimSpace(v) == "" {
			return fallback
		}
		return v
	case nil:
		return fallback
	default:
		return fallback
	}
}

var envKeyRe = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]{0,63}$`)
