package vllm

// vllmComposeYAML renders the vllm-openai service. Two paths:
//
//   - NeedsBuild=false: image: {{vllm_image}} — fastest, no Docker build.
//   - NeedsBuild=true:  build: . + a generated Dockerfile, tagged
//     vllm-{{slug}}:custom so a second deployment with a different pip set
//     doesn't share an image.
//
// The container always sets HF_HOME=/hf-cache (in-container path); the host
// path lives in the .env as HF_CACHE_DIR so docker compose can substitute it
// into the volume mount.
const vllmComposeYAML = `# Auto-generated by server-monitor templates.
name: {{ .Dep.Slug }}

services:
  vllm:
{{- if .NeedsBuild }}
    build:
      context: .
      dockerfile: Dockerfile
    image: vllm-{{ .Dep.Slug }}:custom
{{- else }}
    image: {{ .Config.vllm_image }}
{{- end }}
    container_name: {{ .Dep.Slug }}-vllm
    restart: unless-stopped
    runtime: nvidia
    ipc: host
    shm_size: "16g"
    ports:
      - "${VLLM_PORT}:8000"
    env_file:
      - .env
    environment:
      HF_TOKEN: ${HF_TOKEN}
      HF_HOME: /hf-cache
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      HF_HUB_ENABLE_HF_TRANSFER: "1"
      HF_HUB_ETAG_TIMEOUT: "600"
      HF_HUB_DOWNLOAD_TIMEOUT: "7200"
      VLLM_CACHE_ROOT: /hf-cache/.vllm-cache
      VLLM_WORKER_MULTIPROC_METHOD: spawn
      TOKENIZERS_PARALLELISM: "false"
    volumes:
      - ${HF_CACHE_DIR}:/hf-cache
      - vllm-logs:/var/log/vllm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    command:
      - "--model"
      - {{ yamlQuote .Config.model }}
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--tensor-parallel-size"
      - {{ yamlQuote .Config.tensor_parallel_size }}
      - "--max-model-len"
      - {{ yamlQuote .Config.max_model_len }}
      - "--gpu-memory-utilization"
      - {{ yamlQuote .Config.gpu_memory_utilization }}
      - "--served-model-name"
      - {{ yamlQuote .Config.served_model_name }}
{{- range $arg := .ExtraArgs }}
      - {{ yamlQuote $arg }}
{{- end }}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "5"

volumes:
  vllm-logs:
    driver: local
`
