package vllm

// vllmDockerfile is only emitted when the user supplied extra_pip_packages.
// It mirrors the pattern the user already ran successfully on the host: pin
// HTTPS for apt, install git + ca-certificates so pip can fetch git+...
// URLs, then pip-install each package on its own RUN layer for cache reuse.
const vllmDockerfile = `# Auto-generated by server-monitor templates.
FROM {{ .Config.vllm_image }}

RUN sed -i 's|http://archive.ubuntu.com|https://archive.ubuntu.com|g' /etc/apt/sources.list 2>/dev/null || true \
 && sed -i 's|http://security.ubuntu.com|https://security.ubuntu.com|g' /etc/apt/sources.list 2>/dev/null || true \
 && apt-get update \
 && apt-get install -y --no-install-recommends git ca-certificates \
 && rm -rf /var/lib/apt/lists/*

{{- range $pkg := .PipPackages }}
RUN pip install --no-cache-dir {{ $pkg }}
{{- end }}
`
